[server]
control-plane ansible_host=35.178.82.203 private_ip=10.0.1.245

[agents]
worker-1 ansible_host=13.40.121.155 private_ip=10.0.1.137
worker-2 ansible_host=13.40.53.60 private_ip=10.0.1.18

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=./phoenix-key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
